// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

type Todo struct {
	ID     string
	UserID string
	Text   string
	Done   bool
}

type User struct {
	ID   string
	Name string
}
