// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID          string
	Name        string
	Description pgtype.Text
	Price       pgtype.Float8
}
