// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (
    id,
    name,
    description,
    price)
VALUES (
    $1,
    $2,
    $3,
    $4)
`

type CreateProductParams struct {
	ID          string
	Name        string
	Description pgtype.Text
	Price       pgtype.Float8
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	return err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT
    id, name, description, price
FROM
    products
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
