// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    username,
    email,
    encrypted_password,
    role,
    is_active)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6)
RETURNING
    id, username, email, encrypted_password, role, is_active, created_at, last_login_at
`

type CreateUserParams struct {
	ID                pgtype.UUID
	Username          string
	Email             string
	EncryptedPassword string
	Role              UserRole
	IsActive          bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.EncryptedPassword,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EncryptedPassword,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT
    id,
    username,
    email,
    encrypted_password,
    ROLE,
    is_active,
    created_at,
    last_login_at
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EncryptedPassword,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
