package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/anirudhaxe/go-api-servers/graphql/internal/graph/model"
	"github.com/anirudhaxe/go-api-servers/graphql/internal/repository"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	ctp := repository.CreateTodoParams{ID: input.ID, UserID: input.UserID, Text: input.Text}

	todo, err := r.Repo.CreateTodo(ctx, ctp)
	if err != nil {
		return nil, err
	}

	return &model.Todo{ID: todo.ID, UserID: todo.UserID, Text: todo.Text, Done: todo.Done}, nil

}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	cup := repository.CreateUserParams{ID: input.ID, Name: input.Name}
	usr, err := r.Repo.CreateUser(ctx, cup)

	if err != nil {
		return nil, err
	}

	return &model.User{ID: usr.ID, Name: usr.Name}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todos, err := r.Repo.GetTodos(ctx)
	if err != nil {
		return nil, err
	}
	slice := make([]*model.Todo, len(todos))

	for i, v := range todos {
		slice[i] = &model.Todo{
			ID:     v.ID,
			UserID: v.UserID,
			Text:   v.Text,
			Done:   v.Done,
		}
	}

	return slice, nil

}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {

	usrs, err := r.Repo.GetUsers(ctx)
	if err != nil {
		return nil, err
	}
	slice := make([]*model.User, len(usrs))

	for i, v := range usrs {
		slice[i] = &model.User{
			ID:   v.ID,
			Name: v.Name,
		}
	}

	return slice, nil
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	usr, err := r.Repo.GetUser(ctx, obj.UserID)

	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:   usr.ID,
		Name: usr.Name,
	}, nil

}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
