// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}
